language: ruby
rvm:
  - 2.5.3
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
before_script:
  - psql -c 'create database blog_test' -U postgres
before_install:
- "echo 'gem: --no-document' > ~/.gemrc"
- "echo '--colour' > ~/.rspec"
- export DISPLAY=:99.0
services:
  - xvfb
install:
- bundle install
